### ISSUE TITLE
Paddle-gpu包编译复杂， datas/pkg下存放了与要求环境匹配的whl包

### ISSUE THREAD

**Issue by uniyushu** [Archermmt/yolov3_dcn_nv_hackthon2021#1]
你好，我查看paddlepaddle官方提供的[whl包](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html)，并尝试了[源码编译](https://www.paddlepaddle.org.cn/tutorials/projectdetail/1499138)trt版paddle并没有成功，下面是我的cmake配置
cmake -DPY_VERSION=3 
-DCMAKE_CUDA_ARCHITECTURES=70 
-DWITH_TESTING=OFF 
-DWITH_MKL=ON 
-DWITH_GPU=ON 
-DWITH_TENSORRT=ON
-DTENSORRT_ROOT=/data/TensorRT 
-DON_INFER=ON 
-DCMAKE_BUILD_TYPE=RelWithDebInfo
 ..

能提供下paddle的trt配置，或者提供一下datas/pkg下存放的whl包地址么？

**Comment by Archermmt** [comment]
嗨！你好，这个开源项目是我们为了参加nv的比赛写的一个临时项目，里面paddle的安装只能在比赛的机器上面才能装，paddle trt的安装可以参照paddle官方文档，我们这边的人也是鼓捣了好久才装上，所以项目里面可以使用的部分是tensorrt的engine搭建和测试，paddle部分没办法安装的。
请问用这个项目是要测试tensorrt吗？可以加微信15201213163详谈







在 2021-10-14 10:07:19，"yushu" ***@***.***> 写道：

你好，我查看paddlepaddle官方提供的whl包，并尝试了源码编译trt版paddle并没有成功，下面是我的cmake配置
cmake -DPY_VERSION=3
-DCMAKE_CUDA_ARCHITECTURES=70
-DWITH_TESTING=OFF
-DWITH_MKL=ON
-DWITH_GPU=ON
-DWITH_TENSORRT=ON
-DTENSORRT_ROOT=/data/TensorRT
-DON_INFER=ON
-DCMAKE_BUILD_TYPE=RelWithDebInfo
..

能提供下paddle的trt配置，或者提供一下datas/pkg下存放的whl包地址么？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by uniyushu** [comment]
> 嗨！你好，这个开源项目是我们为了参加nv的比赛写的一个临时项目，里面paddle的安装只能在比赛的机器上面才能装，paddle trt的安装可以参照paddle官方文档，我们这边的人也是鼓捣了好久才装上，所以项目里面可以使用的部分是tensorrt的engine搭建和测试，paddle部分没办法安装的。 请问用这个项目是要测试tensorrt吗？可以加微信15201213163详谈 在 2021-10-14 10:07:19，"yushu" ***@***.***> 写道： 你好，我查看paddlepaddle官方提供的whl包，并尝试了源码编译trt版paddle并没有成功，下面是我的cmake配置 cmake -DPY_VERSION=3 -DCMAKE_CUDA_ARCHITECTURES=70 -DWITH_TESTING=OFF -DWITH_MKL=ON -DWITH_GPU=ON -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/data/TensorRT -DON_INFER=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo .. 能提供下paddle的trt配置，或者提供一下datas/pkg下存放的whl包地址么？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的，就是想测试一下目标检测模型用TensorRT的INT8量化后到底能加速多少，正好看到了你们的项目，感觉你们的项目写得很好，准备自己跑一下试试。
